### ISSUE TITLE
Todos_ASPNETCORE - Hard Typed Return Vals on APIController Endpoints

### ISSUE THREAD

**Issue by SteffenBlake** [samarmohan/backend-frameworks#1]
Endpoints such as:

`public async Task<ActionResult<IEnumerable<Todo>>> GetTodos()`

Can just be

`public async Task<IEnumerable<Todo>> GetTodos()`

**Comment by samarmohan** [comment]
To clarify, I only need ActionResult if I am returning different things from the controller, e.g. JsonResult, FileResult, etc, right?
